spring:
  datasource:
    password: a520rdw2zn94oovb
    url: mysql://b5c9ece09a242f:cfe29b92@eu-cdbr-west-02.cleardb.net/heroku_0a9d5065654408f?reconnect=true
    username: j29btd1pilr4qbei
  jpa:
    hibernate:
      ddl-auto: create-drop
